# -*- coding: utf-8 -*-
"""pfa mixage.ipynb

Automatically generated by Colab.
ls 
Original file is located at
    https://colab.research.google.com/drive/1lahI8XlE7PtnxnNCLSYZs973AZLCrUEC
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import shutil
import random
from pathlib import Path
try:
    from ultralytics import YOLO
except ModuleNotFoundError:
    !pip install -q ultralytics
    from ultralytics import YOLO

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models
from tensorflow.keras.applications import EfficientNetB0

from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    roc_curve,
    auc,
    accuracy_score
)

import matplotlib.pyplot as plt
import seaborn as sns
import os
import shutil

# Dossier d'origine sur Drive (un dossier par classe)
DRIVE_DATA_PATH = "/content/drive/MyDrive/archive (3)/working/dataset_publish/balanced_pest_dataset/train"

print("Contenu DRIVE_DATA_PATH :")
!ls -la "{DRIVE_DATA_PATH}"

# Dossier de travail local
WORKDIR = "/content/dataset_for_experiments"

# Nettoyage + création
if os.path.exists(WORKDIR):
    shutil.rmtree(WORKDIR)
os.makedirs(WORKDIR, exist_ok=True)

print("\n📂 Copie du dataset vers", WORKDIR)

for root, dirs, files in os.walk(DRIVE_DATA_PATH):
    rel_path = os.path.relpath(root, DRIVE_DATA_PATH)
    dest_path = os.path.join(WORKDIR, rel_path)
    os.makedirs(dest_path, exist_ok=True)

    for f in files:
        src_file = os.path.join(root, f)
        dst_file = os.path.join(dest_path, f)
        try:
            shutil.copy2(src_file, dst_file)
        except Exception as e:
            print(f"⚠️ Erreur en copiant {src_file} → ignoré ({e})")

print("\n✅ Copie terminée. Arborescence :")
!find "{WORKDIR}" -maxdepth 2 -type d

""" **data split Data augmentation & DataGenerators (pour le CNN)**"""

!pip install -q split-folders
import splitfolders
import os
import shutil

# dossier du dataset ORIGINAL
WORKDIR = "/content/dataset_for_experiments"

# dossier de sortie
DATA_ROOT = "/content/split_dataset"

# supprimer ancien split s’il existe
shutil.rmtree(DATA_ROOT, ignore_errors=True)

# split
splitfolders.ratio(
    WORKDIR,
    output=DATA_ROOT,
    seed=42,
    ratio=(0.7, 0.2, 0.1)
)

print("✅ Split terminé")

# vérification
!find /content/split_dataset -maxdepth 2 -type d
import os
from tensorflow.keras.preprocessing.image import ImageDataGenerator

img_size   = (224, 224)
batch_size = 32

# Data augmentation pour train
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    zoom_range=0.35,
    width_shift_range=0.20,
    height_shift_range=0.20,
    shear_range=15,
    brightness_range=(0.6, 1.4),
    horizontal_flip=True,
    fill_mode="nearest"
)

# Pas d'augmentation pour val/test
test_val_datagen = ImageDataGenerator(rescale=1./255)
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os

IMG_SIZE = (224, 224)
BATCH_SIZE = 32
DATA_ROOT = "/content/split_dataset"

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    zoom_range=0.35,
    width_shift_range=0.20,
    height_shift_range=0.20,
    shear_range=15,
    brightness_range=(0.6, 1.4),
    horizontal_flip=True,
    fill_mode="nearest"
)

val_test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    os.path.join(DATA_ROOT, "train"),
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    shuffle=True
)

val_generator = val_test_datagen.flow_from_directory(
    os.path.join(DATA_ROOT, "val"),
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    shuffle=False
)

test_generator = val_test_datagen.flow_from_directory(
    os.path.join(DATA_ROOT, "test"),
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    shuffle=False
)
import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

# Labels du train
y_train = train_generator.classes
class_labels = np.unique(y_train)

# Calcul des poids pour chaque classe
class_weights_values = compute_class_weight(
    class_weight="balanced",
    classes=class_labels,
    y=y_train
)

class_weights = dict(zip(class_labels, class_weights_values))
print("Class weights :", class_weights)

"""** mixage **"""

# ============================
# 📦 IMPORTS
# ============================
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc
import torch

# YOLO
try:
    from ultralytics import YOLO
except ModuleNotFoundError:
    import subprocess, sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "ultralytics"])
    from ultralytics import YOLO

# ============================
# 1️⃣ PARAMÈTRES & CHEMINS
# ============================
DATA_ROOT = "/content/split_dataset"

CNN_PATH  = "/content/drive/MyDrive/pest_model_project/cnn_pest_best.h5"
YOLO_PATH = "/content/drive/MyDrive/yolo_runs/yolo_pest_cls_fast_cpu/weights/best.pt"

img_size   = (224, 224)
batch_size = 32

VAL_DIR  = os.path.join(DATA_ROOT, "val")
TEST_DIR = os.path.join(DATA_ROOT, "test")

# ============================
# 2️⃣ GÉNÉRATEURS
# ============================
datagen = ImageDataGenerator(rescale=1./255)

val_generator = datagen.flow_from_directory(
    VAL_DIR, target_size=img_size,
    batch_size=batch_size, class_mode="categorical",
    shuffle=False
)

test_generator = datagen.flow_from_directory(
    TEST_DIR, target_size=img_size,
    batch_size=batch_size, class_mode="categorical",
    shuffle=False
)

class_names = list(val_generator.class_indices.keys())
num_classes = len(class_names)

y_true_val  = val_generator.classes
y_true_test = test_generator.classes

print("\n✅ Classes :", class_names)
print("Nombre de classes :", num_classes)

# ============================
# 3️⃣ CNN — PRÉDICTIONS
# ============================
cnn_model = tf.keras.models.load_model(CNN_PATH, compile=False)

cnn_probs_val  = cnn_model.predict(val_generator, verbose=1)
cnn_probs_test = cnn_model.predict(test_generator, verbose=1)

y_pred_cnn_val  = np.argmax(cnn_probs_val, axis=1)
y_pred_cnn_test = np.argmax(cnn_probs_test, axis=1)

acc_cnn_val  = accuracy_score(y_true_val, y_pred_cnn_val)
acc_cnn_test = accuracy_score(y_true_test, y_pred_cnn_test)

print(f"\n📊 Accuracy CNN (val)  : {acc_cnn_val:.4f}")
print(f"📊 Accuracy CNN (test) : {acc_cnn_test:.4f}")

# ============================
# 4️⃣ YOLO — PRÉDICTIONS
# ============================
if os.path.isfile(YOLO_PATH):
    torch.cuda.empty_cache()
    yolo_model = YOLO(YOLO_PATH)

    def yolo_predict(filepaths, imgsz=224):
        probs = []
        for img in filepaths:
            r = yolo_model(img, imgsz=imgsz, device="cpu", verbose=False)[0]
            probs.append(r.probs.data.cpu().numpy())
        return np.array(probs)

    val_paths  = val_generator.filepaths
    test_paths = test_generator.filepaths

    yolo_probs_val  = yolo_predict(val_paths)
    yolo_probs_test = yolo_predict(test_paths)

    y_pred_yolo_val  = np.argmax(yolo_probs_val, axis=1)
    y_pred_yolo_test = np.argmax(yolo_probs_test, axis=1)

    acc_yolo_val  = accuracy_score(y_true_val, y_pred_yolo_val)
    acc_yolo_test = accuracy_score(y_true_test, y_pred_yolo_test)

    print(f"\n📊 Accuracy YOLO (val)  : {acc_yolo_val:.4f}")
    print(f"📊 Accuracy YOLO (test) : {acc_yolo_test:.4f}")
else:
    print(f"\n⚠️ Fichier YOLO non trouvé : {YOLO_PATH}")
    print("✅ Utilisation de probabilités aléatoires pour YOLO.")
    np.random.seed(42)
    yolo_probs_val  = np.random.rand(len(y_true_val), num_classes)
    yolo_probs_val  /= yolo_probs_val.sum(axis=1, keepdims=True)
    yolo_probs_test = np.random.rand(len(y_true_test), num_classes)
    yolo_probs_test /= yolo_probs_test.sum(axis=1, keepdims=True)

    y_pred_yolo_val  = np.argmax(yolo_probs_val, axis=1)
    y_pred_yolo_test = np.argmax(yolo_probs_test, axis=1)

    acc_yolo_val  = accuracy_score(y_true_val, y_pred_yolo_val)
    acc_yolo_test = accuracy_score(y_true_test, y_pred_yolo_test)

# ============================
# 5️⃣ ENSEMBLE PONDÉRÉ
# ============================
alpha = 0.85  # YOLO dominant
beta  = 0.15  # CNN secondaire

min_len_val  = min(len(cnn_probs_val), len(yolo_probs_val))
min_len_test = min(len(cnn_probs_test), len(yolo_probs_test))

ens_weighted_val  = alpha*yolo_probs_val[:min_len_val]  + beta*cnn_probs_val[:min_len_val]
ens_weighted_test = alpha*yolo_probs_test[:min_len_test] + beta*cnn_probs_test[:min_len_test]

y_pred_weighted_val  = np.argmax(ens_weighted_val, axis=1)
y_pred_weighted_test = np.argmax(ens_weighted_test, axis=1)

acc_weighted_val  = accuracy_score(y_true_val[:min_len_val], y_pred_weighted_val)
acc_weighted_test = accuracy_score(y_true_test[:min_len_test], y_pred_weighted_test)

print(f"\n📊 Accuracy ENSEMBLE pondéré (val)  : {acc_weighted_val:.4f}")
print(f"📊 Accuracy ENSEMBLE pondéré (test) : {acc_weighted_test:.4f}")

# ============================
# 6️⃣ ENSEMBLE INTELLIGENT (FINAL 🔥)
# ============================
def smart_ensemble(cnn_probs, yolo_probs, threshold=0.75):
    final_probs = []
    for c, y in zip(cnn_probs, yolo_probs):
        if np.max(c) > threshold:
            final_probs.append((c + y) / 2)
        else:
            final_probs.append(y)
    return np.array(final_probs)

ens_smart_val  = smart_ensemble(cnn_probs_val[:min_len_val], yolo_probs_val[:min_len_val])
ens_smart_test = smart_ensemble(cnn_probs_test[:min_len_test], yolo_probs_test[:min_len_test])

y_pred_smart_val  = np.argmax(ens_smart_val, axis=1)
y_pred_smart_test = np.argmax(ens_smart_test, axis=1)

acc_smart_val  = accuracy_score(y_true_val[:min_len_val], y_pred_smart_val)
acc_smart_test = accuracy_score(y_true_test[:min_len_test], y_pred_smart_test)

print(f"\n🔥 Accuracy ENSEMBLE intelligent (val)  : {acc_smart_val:.4f}")
print(f"🔥 Accuracy ENSEMBLE intelligent (test) : {acc_smart_test:.4f}")

# ============================
# 7️⃣ MATRICE DE CONFUSION
# ============================
def plot_confusion(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(12,10))
    sns.heatmap(cm, cmap="Blues", xticklabels=class_names, yticklabels=class_names)
    plt.title(title)
    plt.xlabel("Prédit")
    plt.ylabel("Réel")
    plt.xticks(rotation=90)
    plt.show()
    print(classification_report(y_true, y_pred, target_names=class_names))

plot_confusion(y_true_test[:min_len_test], y_pred_smart_test, "Ensemble intelligent — Test")

# ============================
# 8️⃣ BAR CHART FINAL
# ============================
def plot_bar(accs, labels, title):
    plt.figure(figsize=(7,5))
    bars = plt.bar(labels, accs)
    for b, a in zip(bars, accs):
        plt.text(b.get_x()+b.get_width()/2, b.get_height()+0.01, f"{a:.3f}", ha="center")
    plt.ylim(0,1)
    plt.title(title)
    plt.grid(axis="y", alpha=0.3)
    plt.show()

plot_bar(
    [acc_cnn_test, acc_yolo_test, acc_smart_test],
    ["CNN", "YOLO", "ENSEMBLE intelligent"],
    "Accuracy — Comparaison finale (Test)"
)

"""**Matrice de confusion + classification report (ensemble)**"""

# ============================================
# 📦 ENSEMBLE CNN + YOLO ROBUSTE
# ============================================
import os
import sys
import subprocess
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import torch

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, auc
from sklearn.preprocessing import label_binarize

# ---------- 0) Import / install YOLO ----------
try:
    from ultralytics import YOLO
except ModuleNotFoundError:
    print("⚠️ 'ultralytics' non installé. Installation en cours...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "ultralytics"])
    from ultralytics import YOLO
    print("✅ 'ultralytics' installé avec succès.")

# ---------------------------
# 1) Paramètres & chemins
# ---------------------------

DATA_ROOT = "/content/split_dataset"  # ton dataset
TEST_DIR  = os.path.join(DATA_ROOT, "test")

CNN_PATH  = "/content/drive/MyDrive/pest_model_project/cnn_pest_best.h5"
YOLO_PATH = "/content/drive/MyDrive/yolo_runs/yolo_pest_cls_fast_cpu/weights/best.pt"

img_size   = (224, 224)
batch_size = 32

# Vérification du dossier test
if not os.path.isdir(TEST_DIR):
    raise FileNotFoundError(f"❌ Le dossier test n'existe pas à l'emplacement : {TEST_DIR}")

# ---------------------------
# 2) Test generator
# ---------------------------
test_datagen = ImageDataGenerator(rescale=1.0/255)

test_generator = test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=img_size,
    batch_size=batch_size,
    class_mode="categorical",
    shuffle=False
)

class_names = list(test_generator.class_indices.keys())
num_classes = len(class_names)
y_true = test_generator.classes

print("\n🔎 Classes :", class_names)
print("Nombre de classes :", num_classes)
print("Nombre d'images test :", len(y_true))

# ---------------------------
# 3) CNN — Prédictions
# ---------------------------
if not os.path.isfile(CNN_PATH):
    raise FileNotFoundError(f"❌ Fichier modèle CNN introuvable : {CNN_PATH}")

cnn_model = tf.keras.models.load_model(CNN_PATH, compile=False)
print("\n✅ Modèle CNN chargé depuis :", CNN_PATH)

cnn_probs = cnn_model.predict(test_generator, verbose=1)
y_pred_cnn = np.argmax(cnn_probs, axis=1)
acc_cnn = accuracy_score(y_true, y_pred_cnn)
print(f"\n📊 Accuracy CNN : {acc_cnn:.4f}")

# ---------------------------
# 4) YOLO — Prédictions
# ---------------------------
if os.path.isfile(YOLO_PATH):
    # Nettoyage mémoire GPU
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    yolo_model = YOLO(YOLO_PATH)
    print("\n✅ Modèle YOLO chargé depuis :", YOLO_PATH)

    # Stream pour éviter Out of Memory
    test_filepaths = test_generator.filepaths
    yolo_probs_list = []
    yolo_results_pred = yolo_model(
        source=test_filepaths,
        imgsz=224,
        stream=True,
        device="cpu",
        batch=16,
        verbose=False
    )

    for r in yolo_results_pred:
        probs = r.probs.numpy()
        yolo_probs_list.append(probs)

    yolo_probs = np.stack(yolo_probs_list, axis=0)
    y_pred_yolo = np.argmax(yolo_probs, axis=1)
    acc_yolo = accuracy_score(y_true, y_pred_yolo)
    print(f"📊 Accuracy YOLO : {acc_yolo:.4f}")
else:
    raise FileNotFoundError(f"❌ Fichier modèle YOLO introuvable : {YOLO_PATH}")

# ---------------------------
# 5) Ensemble CNN + YOLO
# ---------------------------
assert cnn_probs.shape == yolo_probs.shape, "Incohérence de dimensions entre CNN et YOLO !"
ens_probs = (cnn_probs + yolo_probs) / 2.0
y_pred_ens = np.argmax(ens_probs, axis=1)
acc_ens = accuracy_score(y_true, y_pred_ens)
print(f"📊 Accuracy Ensemble (CNN + YOLO) : {acc_ens:.4f}")

# ---------------------------
# 6) Matrice de confusion + classification report
# ---------------------------
cm_ens = confusion_matrix(y_true, y_pred_ens)

plt.figure(figsize=(12, 10))
sns.heatmap(cm_ens, annot=False, cmap="Blues", xticklabels=class_names, yticklabels=class_names)
plt.title("Matrice de confusion - Ensemble (CNN + YOLO)")
plt.xlabel("Prédit")
plt.ylabel("Réel")
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

print("\nClassification report - Ensemble (CNN + YOLO)")
print(classification_report(y_true, y_pred_ens, target_names=class_names))

# ---------------------------
# 7) Courbe ROC macro
# ---------------------------
y_true_bin = label_binarize(y_true, classes=np.arange(num_classes))

fpr = {}
tpr = {}
roc_auc = {}
for i in range(num_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], ens_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

all_fpr = np.unique(np.concatenate([fpr[i] for i in range(num_classes)]))
mean_tpr = np.zeros_like(all_fpr)
for i in range(num_classes):
    mean_tpr += np.interp(all_fpr, fpr[i], tpr[i])
mean_tpr /= num_classes
roc_auc_macro = auc(all_fpr, mean_tpr)

plt.figure(figsize=(8, 6))
plt.plot(all_fpr, mean_tpr, label=f"ROC macro Ensemble (AUC = {roc_auc_macro:.3f})")
plt.plot([0, 1], [0, 1], "k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Courbe ROC macro - Ensemble (CNN + YOLO)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# ---------------------------
# 8) Bar chart CNN vs YOLO vs Ensemble
# ---------------------------
models = ["CNN", "YOLO", "Ensemble"]
accuracies = [acc_cnn, acc_yolo, acc_ens]

plt.figure(figsize=(7, 5))
bars = plt.bar(models, accuracies)
for bar, acc in zip(bars, accuracies):
    y = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, y + 0.005, f"{acc:.3f}", ha="center", va="bottom")

plt.ylim(0, 1.0)
plt.ylabel("Accuracy sur test")
plt.title("Comparaison des performances : CNN vs YOLO vs Ensemble")
plt.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.show()

"""**Validation sur /val (CNN + YOLO + Ensemble)**"""

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from ultralytics import YOLO

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    auc
)
from sklearn.preprocessing import label_binarize
import torch

# ---------------------------
# 1) Chemins + paramètres
# ---------------------------
DATA_ROOT = "/content/split_dataset"
VAL_DIR   = os.path.join(DATA_ROOT, "val")

# ✅ Assure-toi que les chemins sont corrects
CNN_PATH = "/content/drive/MyDrive/pest_model_project/cnn_pest_best.h5"

YOLO_PATH = "/content/drive/MyDrive/yolo_runs/yolov8_pest_cls_fast_cpu/weights/best.pt"
img_size   = (224, 224)
batch_size = 32

# ---------------------------
# 2) Générateur VAL (sans augmentation)
# ---------------------------
val_datagen = ImageDataGenerator(rescale=1.0/255)

val_generator = val_datagen.flow_from_directory(
    VAL_DIR,
    target_size=img_size,
    batch_size=batch_size,
    class_mode="categorical",
    shuffle=False
)

class_names = list(val_generator.class_indices.keys())
num_classes = len(class_names)
y_true = val_generator.classes

print("\n✅ Validation set")
print("Nombre d'images val :", len(y_true))
print("Nombre de classes   :", num_classes)

# ---------------------------
# 3) CNN : probas + métriques
# ---------------------------
if not os.path.isfile(CNN_PATH):
    raise FileNotFoundError(f"❌ Fichier CNN introuvable : {CNN_PATH}")

cnn_model = tf.keras.models.load_model(CNN_PATH)
print("\n✅ CNN chargé :", CNN_PATH)

cnn_probs = cnn_model.predict(val_generator, verbose=1)
y_pred_cnn = np.argmax(cnn_probs, axis=1)

acc_cnn = accuracy_score(y_true, y_pred_cnn)
print(f"\n📊 Accuracy CNN (val) : {acc_cnn:.4f}")

# ---------------------------
# 4) YOLO : probas + métriques (stream=True pour éviter RAM/OOM)
# ---------------------------
if not os.path.isfile(YOLO_PATH):
    raise FileNotFoundError(f"❌ Fichier YOLO introuvable : {YOLO_PATH}")

# Nettoyage mémoire GPU/CPU
if torch.cuda.is_available():
    torch.cuda.empty_cache()

yolo_model = YOLO(YOLO_PATH)
print("\n✅ YOLO chargé :", YOLO_PATH)

val_filepaths = val_generator.filepaths

# ⚠️ Utilise device="cpu" si tu n'as pas assez de VRAM
yolo_results_stream = yolo_model(
    source=val_filepaths,
    imgsz=224,
    device="cpu",
    stream=True,
    verbose=False
)

yolo_probs_list = []
for r in yolo_results_stream:
    # r.probs peut être None si YOLO n'a rien détecté → fallback
    if r.probs is not None:
        yolo_probs_list.append(r.probs.cpu().numpy())
    else:
        yolo_probs_list.append(np.zeros(num_classes))

yolo_probs = np.stack(yolo_probs_list, axis=0)
y_pred_yolo = np.argmax(yolo_probs, axis=1)

acc_yolo = accuracy_score(y_true, y_pred_yolo)
print(f"📊 Accuracy YOLO (val) : {acc_yolo:.4f}")

# ---------------------------
# 5) Ensemble : moyenne des probas
# ---------------------------
# Vérification shape
if cnn_probs.shape != yolo_probs.shape:
    min_len = min(len(cnn_probs), len(yolo_probs))
    cnn_probs = cnn_probs[:min_len]
    yolo_probs = yolo_probs[:min_len]
    y_true = y_true[:min_len]

ens_probs = (cnn_probs + yolo_probs) / 2.0
y_pred_ens = np.argmax(ens_probs, axis=1)

acc_ens = accuracy_score(y_true, y_pred_ens)
print(f"📊 Accuracy ENSEMBLE (val) : {acc_ens:.4f}")

# ---------------------------
# 6) Matrice de confusion + report (ENSEMBLE)
# ---------------------------
cm = confusion_matrix(y_true, y_pred_ens)

plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=False, cmap="Blues", xticklabels=class_names, yticklabels=class_names)
plt.title("Matrice de confusion - Ensemble (val)")
plt.xlabel("Prédit")
plt.ylabel("Réel")
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.show()

print("\nClassification report - Ensemble (val)")
print(classification_report(y_true, y_pred_ens, target_names=class_names))

# ---------------------------
# 7) ROC macro (ENSEMBLE)
# ---------------------------
y_true_bin = label_binarize(y_true, classes=np.arange(num_classes))

fpr = {}
tpr = {}
roc_auc = {}

for i in range(num_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], ens_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

all_fpr = np.unique(np.concatenate([fpr[i] for i in range(num_classes)]))
mean_tpr = np.zeros_like(all_fpr)
for i in range(num_classes):
    mean_tpr += np.interp(all_fpr, fpr[i], tpr[i])
mean_tpr /= num_classes

roc_auc_macro = auc(all_fpr, mean_tpr)

plt.figure(figsize=(8, 6))
plt.plot(all_fpr, mean_tpr, label=f"ROC macro (AUC = {roc_auc_macro:.3f})")
plt.plot([0, 1], [0, 1], "k--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Courbe ROC macro - Ensemble (val)")
plt.legend()
plt.grid(True)
plt.show()

# ---------------------------
# 8) Comparaison finale (bar chart)
# ---------------------------
models = ["CNN", "YOLO", "Ensemble"]
accs = [acc_cnn, acc_yolo, acc_ens]

plt.figure(figsize=(7, 5))
bars = plt.bar(models, accs)
for b, a in zip(bars, accs):
    plt.text(b.get_x() + b.get_width()/2, b.get_height() + 0.005, f"{a:.3f}",
             ha="center", va="bottom")
plt.ylim(0, 1.0)
plt.ylabel("Accuracy sur validation")
plt.title("Comparaison des performances sur validation")
plt.grid(axis="y", alpha=0.3)
plt.show()
# ====================================================
# 🦗 TEST FINAL — DÉTECTION DE CRIQUETS AVEC POURCENTAGE
# ====================================================

import os
import random
import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO

# =========================
# PARAMÈTRES
# =========================
VAL_DIR = "/content/drive/.Encrypted/MyDrive/archive (3)/working/dataset_publish/balanced_pest_dataset/val"
YOLO_MODEL_PATH = "/content/drive/MyDrive/yolo_runs/yolo_pest_cls_fast_cpu/weights/best.pt"

TARGET_CLASS = "Grasshopper"
CONF_THRESHOLD = 70     # % minimum
N_IMAGES = 8            # nombre d'images à afficher


# =========================
# COLLECTE DES IMAGES
# =========================
all_images = []

for cls in os.listdir(VAL_DIR):
    cls_path = os.path.join(VAL_DIR, cls)
    if os.path.isdir(cls_path):
        for img in os.listdir(cls_path):
            if img.lower().endswith((".jpg", ".png", ".jpeg")):
                all_images.append(os.path.join(cls_path, img))

print(f"✅ {len(all_images)} images trouvées pour le test.")

# Sélection aléatoire
sample_images = random.sample(all_images, min(N_IMAGES, len(all_images)))


# =========================
# CHARGEMENT DU MODÈLE YOLO
# =========================
model = YOLO(YOLO_MODEL_PATH)

results = model(sample_images, imgsz=160, device="cpu", verbose=False)


# =========================
# AFFICHAGE DES RÉSULTATS
# =========================
plt.figure(figsize=(16, 8))

for i, (img_path, r) in enumerate(zip(sample_images, results)):
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    pred_class = r.names[r.probs.top1]
    confidence = float(r.probs.top1conf) * 100

    if pred_class == TARGET_CLASS and confidence >= CONF_THRESHOLD:
        decision = "🦗 CRIQUET DÉTECTÉ"
        color = "green"
    else:
        decision = "❌ NON CRIQUET"
        color = "red"

    plt.subplot(2, (N_IMAGES + 1)//2, i + 1)
    plt.imshow(img)
    plt.axis("off")
    plt.title(
        f"{pred_class} — {confidence:.1f}%\n{decision}",
        color=color,
        fontsize=11
    )

plt.suptitle("🦗 Détection de criquets — YOLOv8 Classification", fontsize=16)
plt.tight_layout()
plt.show()